ALJAZEERA_DATE_SEPARATORS = '...'
ALJAZEERA_SCRAPE_URL = 'https://www.aljazeera.com/'

TITLE_KEY = 'title'
DESCRIPTION_KEY = 'description'
IMAGE_PATH = 'image_path'
PUBLISH_DATE = 'publish_date'

SEARCH_PHRASE = 'SEARCH_PHRASE'
MONTH = 'MONTH'
CONFIG_KEYS = [SEARCH_PHRASE, MONTH]
